# Car test-time prediction

## Loading MB dataset

In [24]:
import pandas as pd
data = pd.read_csv('mercedes_test.csv')

In [25]:
# Figure out "m" and "features"
data
# m=4209, n=376

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 378 columns]

In [27]:
data.head(5)

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[5 rows x 378 columns]

In [28]:
data.tail(5)

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[5 rows x 378 columns]

## Data pre-processing

In [29]:
# Choose categorical data
data_temp = data.select_dtypes(include=['object'])
data_temp

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

In [30]:
# Choose categorical data columns
cf = data.select_dtypes(include=['object']).columns
print(cf)

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')


In [31]:
# To change it into "categorical" data type
data[cf]=data[cf].astype('category')

In [32]:
# One hot encoding
data = pd.get_dummies(data)
print(data)

        ID       y  X10  X11  X12  X13  X14  X15  X16  X17  ...  X8_p  X8_q  \
0        0  130.81    0    0    0    1    0    0    0    0  ...     0     0   
1        6   88.53    0    0    0    0    0    0    0    0  ...     0     0   
2        7   76.26    0    0    0    0    0    0    0    1  ...     0     0   
3        9   80.62    0    0    0    0    0    0    0    0  ...     0     0   
4       13   78.02    0    0    0    0    0    0    0    0  ...     0     0   
...    ...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
4204  8405  107.39    0    0    0    0    1    0    0    0  ...     0     1   
4205  8406  108.77    0    0    0    0    0    0    0    0  ...     0     0   
4206  8412  109.22    0    0    1    1    0    0    0    0  ...     0     0   
4207  8415   87.48    0    0    0    0    1    0    0    0  ...     0     0   
4208  8417  110.85    0    0    0    0    0    0    0    0  ...     0     0   

      X8_r  X8_s  X8_t  X8_u  X8_v  X8_w  X8_x  X8_

In [33]:
# Obtain X from data (excluding 'ID' and 'y')
X_df = data.drop(['ID','y'],axis=1)
# Obtain y from data
y_df = data['y']
print(X_df)
print(y_df)

      X10  X11  X12  X13  X14  X15  X16  X17  X18  X19  ...  X8_p  X8_q  X8_r  \
0       0    0    0    1    0    0    0    0    1    0  ...     0     0     0   
1       0    0    0    0    0    0    0    0    1    0  ...     0     0     0   
2       0    0    0    0    0    0    0    1    0    0  ...     0     0     0   
3       0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
4       0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
4204    0    0    0    0    1    0    0    0    0    0  ...     0     1     0   
4205    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   
4206    0    0    1    1    0    0    0    0    0    0  ...     0     0     0   
4207    0    0    0    0    1    0    0    0    0    0  ...     0     0     0   
4208    0    0    0    0    0    0    0    0    0    0  ...     0     0     0   

      X8_s  X8_t  X8_u  X8_

In [34]:
# Convert y_df into binary labels
import numpy as np
TF_vector= (y_df<np.median(y_df))
y_df=TF_vector.astype(float)
print(TF_vector)
print(y_df)

0       False
1        True
2        True
3        True
4        True
        ...  
4204    False
4205    False
4206    False
4207     True
4208    False
Name: y, Length: 4209, dtype: bool
0       0.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
4204    0.0
4205    0.0
4206    0.0
4207    1.0
4208    0.0
Name: y, Length: 4209, dtype: float64


In [35]:
# Conver data frame into numpy array
X,y = X_df.values, y_df.values
print(X)
print(X.shape)
print(y)
print(y.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
(4209, 563)
[0. 1. 1. ... 0. 1. 0.]
(4209,)


## Split into train and test datasets

In [36]:
from sklearn.model_selection import train_test_split
#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,stratify=y)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,shuffle=False)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3788, 563)
(421, 563)
(3788,)
(421,)


## Least Squares: Hyperparameter search via cross validation 

In [37]:
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import RandomizedSearchCV

model_LS = RidgeClassifier()
#grid_LS = dict(alpha = [10,1,1e-1,1e-2,1e-3])
grid_LS = {'alpha':[10,1,1e-1,1e-2,1e-3]}
cv_LS = RandomizedSearchCV(model_LS,grid_LS,n_iter=5,cv=5)
#cv_LS = RandomizedSearchCV(model_LS,grid_LS,n_iter=5,cv=5,random_state=42)
cv_LS.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=RidgeClassifier(), n_iter=5,
                   param_distributions={'alpha': [10, 1, 0.1, 0.01, 0.001]})

In [38]:
cv_LS.cv_results_ #logs results

{'mean_fit_time': array([0.03251195, 0.03191428, 0.03809786, 0.03331037, 0.0375    ]),
 'std_fit_time': array([0.00173904, 0.00063083, 0.01187476, 0.00101714, 0.00753198]),
 'mean_score_time': array([0.00139623, 0.00099792, 0.00159774, 0.00099769, 0.00159712]),
 'std_score_time': array([4.88091069e-04, 7.77697870e-07, 7.97978480e-04, 1.90734863e-07,
        7.97015978e-04]),
 'param_alpha': masked_array(data=[10, 1, 0.1, 0.01, 0.001],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'alpha': 10},
  {'alpha': 1},
  {'alpha': 0.1},
  {'alpha': 0.01},
  {'alpha': 0.001}],
 'split0_test_score': array([0.90633245, 0.90105541, 0.90237467, 0.90369393, 0.90369393]),
 'split1_test_score': array([0.89050132, 0.88258575, 0.87335092, 0.87335092, 0.87335092]),
 'split2_test_score': array([0.88654354, 0.88390501, 0.87994723, 0.87994723, 0.87994723]),
 'split3_test_score': array([0.84676354, 0.84544254, 0.84412153, 0.84544254, 0.

In [39]:
cv_LS.best_params_

{'alpha': 10}

## Store logs into csv file

In [40]:
# Store logs into csv file
import pandas as pd 
df_LS = pd.DataFrame.from_dict(cv_LS.cv_results_,orient='columns')
# Select columns to be stored
columns = ['params','mean_test_score','std_test_score','rank_test_score'] 
df_LS = df_LS[columns]
df_LS.to_csv("logs_LS.csv")

## Save the best model

In [41]:
best_model_LS=cv_LS.best_estimator_
from joblib import dump
dump(best_model_LS, 'best_model_LS.joblib')

['best_model_LS.joblib']

## Load "best_model_LS.joblib'

In [42]:
from joblib import load
loaded_model_LS = load('best_model_LS.joblib')
loaded_model_LS.score(X_test,y_test)

0.8954869358669834