In [4]:
from shap.datasets import adult

X, y = adult()

print(X)
print(y)

        Age  Workclass  Education-Num  Marital Status  Occupation  \
0      39.0          7           13.0               4           1   
1      50.0          6           13.0               2           4   
2      38.0          4            9.0               0           6   
3      53.0          4            7.0               2           6   
4      28.0          4           13.0               2          10   
...     ...        ...            ...             ...         ...   
32556  27.0          4           12.0               2          13   
32557  40.0          4            9.0               2           7   
32558  58.0          4            9.0               6           1   
32559  22.0          4            9.0               4           1   
32560  52.0          5            9.0               2           4   

       Relationship  Race  Sex  Capital Gain  Capital Loss  Hours per week  \
0                 0     4    1        2174.0           0.0            40.0   
1              

In [3]:
pip install shap

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 533.5/533.5 kB 3.4 MB/s eta 0:00:00


In [5]:
numerical_columns = ['Age','Education-Num','Capital Gain','Capital Loss','Hours per week']
categorical_columns = ['Workclass','Marital Status','Occupation','Relationship','Race','Sex','Country']


## Conversion of categorical data

In [6]:
import pandas as pd # for one-hot encoding

from sklearn.preprocessing import StandardScaler # for normalization

In [7]:
# Normalization of numerical data
for column in numerical_columns:
    scaler = StandardScaler()
    X[column] = scaler.fit_transform(X[column].values.reshape(-1,1))

print(X)

            Age  Workclass  Education-Num  Marital Status  Occupation  \
0      0.030671          7       1.134739               4           1   
1      0.837109          6       1.134739               2           4   
2     -0.042642          4      -0.420060               0           6   
3      1.057047          4      -1.197459               2           6   
4     -0.775768          4       1.134739               2          10   
...         ...        ...            ...             ...         ...   
32556 -0.849080          4       0.746039               2          13   
32557  0.103983          4      -0.420060               2           7   
32558  1.423610          4      -0.420060               6           1   
32559 -1.215643          4      -0.420060               4           1   
32560  0.983734          5      -0.420060               2           4   

       Relationship  Race  Sex  Capital Gain  Capital Loss  Hours per week  \
0                 0     4    1      0.148453 

In [8]:
# Data type change of categorical data
for column in categorical_columns:
    X[column] = X[column].astype('category')

print(X)

            Age Workclass  Education-Num Marital Status Occupation  \
0      0.030671         7       1.134739              4          1   
1      0.837109         6       1.134739              2          4   
2     -0.042642         4      -0.420060              0          6   
3      1.057047         4      -1.197459              2          6   
4     -0.775768         4       1.134739              2         10   
...         ...       ...            ...            ...        ...   
32556 -0.849080         4       0.746039              2         13   
32557  0.103983         4      -0.420060              2          7   
32558  1.423610         4      -0.420060              6          1   
32559 -1.215643         4      -0.420060              4          1   
32560  0.983734         5      -0.420060              2          4   

      Relationship Race Sex  Capital Gain  Capital Loss  Hours per week  \
0                0    4   1      0.148453      -0.21666       -0.035429   
1        

In [9]:
# One-hot encoding of categorical data
X = pd.get_dummies(X)

# Conversion of data frame to numpy
X = X.values

# Converision: {False, True} --> {0., 1.}
y = y.astype(float)

In [10]:
print(X.shape)
print(y.shape)
print(y)

(32561, 91)
(32561,)
[0. 0. 0. ... 0. 0. 1.]


## train-val-test split

In [11]:
from sklearn.model_selection import train_test_split

X_,X_test,y_,y_test = train_test_split(X,y,test_size=1/10,stratify=y)
X_train,X_val,y_train,y_val = train_test_split(X_,y_,test_size=1/9,stratify=y_)

print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(26048, 91)
(3256, 91)
(3257, 91)


## Cross validation

In [12]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

X1  = np.array([10, 20, 30, 40, 50])
y1  = np.array([60, 70, 80, 90, 100])

kfold = KFold(n_splits=4,shuffle=True)

X1_,X1_test,y1_,y1_test = train_test_split(X1,y1,test_size=1/5)

print(kfold.get_n_splits())
print(X1_)
print(y1_)

4
[40 10 50 30]
[ 90  60 100  80]


In [13]:
for train, val in kfold.split(X1_,y1_):
    print("Train indices: ",train)
    X1_train = X1_[train]
    print("Train datasets: ",X1_train)

Train indices:  [0 2 3]
Train datasets:  [40 50 30]
Train indices:  [0 1 2]
Train datasets:  [40 10 50]
Train indices:  [1 2 3]
Train datasets:  [10 50 30]
Train indices:  [0 1 3]
Train datasets:  [40 10 30]


In [14]:
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

#kfold = KFold(n_splits=4, shuffle=True)
kfold = KFold(n_splits=4)

X_,X_test,y_,y_test = train_test_split(X,y,test_size=1/10,stratify=y)

aaa = kfold.split(X_,y_)

for train, val in aaa:
    print(train)
    #print(val)
    X_train = X[train]
    print(X_train[0])
   # print(X_train.shape)

[ 7326  7327  7328 ... 29301 29302 29303]
[-0.11595462  0.7460392  -0.14592049 -0.21665953 -0.19740899  0.
  0.          0.          0.          0.          0.          0.
  1.          0.          1.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          1.          0.          0.          0.
  1.          0.          0.          0.          0.          0.
  0.          0.          1.          0.          0.          0.
  1.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.        

In [15]:
def scheduler(epoch, lr):
    if epoch in [20,40,60]:
        lr = 0.1*lr
    else:
        lr = lr
    return lr

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.initializers import HeNormal
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import ReLU
from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import LearningRateScheduler

from sklearn.model_selection import KFold

kfold = KFold(n_splits=4, shuffle=True)

X_,X_test,y_,y_test = train_test_split(X,y,test_size=1/10,stratify=y)

for train, val in kfold.split(X_,y_):

    # Train and val datasets
    X_train, X_val = X[train], X[val]
    y_train, y_val = y[train], y[val]
    #print(X_train.shape)
    #print(X_val.shape)

    # Construct a model
    init = HeNormal()
    model = Sequential()
    model.add(Dense(128,kernel_regularizer=l2(0.01),
              bias_regularizer=l2(0.01),
              kernel_initializer=init))
    model.add(BatchNormalization())
    model.add(ReLU())
    model.add(Dropout(0.5))
    model.add(Dense(1,activation='sigmoid'))

    # Compile
    opt = Adam(learning_rate=0.01,beta_1 = 0.9,beta_2 = 0.999)
    model.compile(optimizer=opt,
                 loss='binary_crossentropy',
                 metrics=['acc'])

    # Early stopping & learning rate decaying
    es_callback = EarlyStopping(monitor='val_acc',patience=15)
    ls_callback = LearningRateScheduler(scheduler)

    # Training
    hist = model.fit(X_train, y_train, epochs=100,
                        validation_data=(X_val,y_val),
                        callbacks=[es_callback,ls_callback])
    # Valiation performance
    print(model.evaluate(X_val, y_val))

Epoch 1/100
687/687 [==============================] - 12s 6ms/step - loss: 0.5063 - acc: 0.8258 - val_loss: 0.4417 - val_acc: 0.8358 - lr: 0.0100
Epoch 2/100
687/687 [==============================] - 3s 4ms/step - loss: 0.4478 - acc: 0.8324 - val_loss: 0.4253 - val_acc: 0.8291 - lr: 0.0100
Epoch 3/100
687/687 [==============================] - 3s 4ms/step - loss: 0.4383 - acc: 0.8318 - val_loss: 0.4300 - val_acc: 0.8288 - lr: 0.0100
Epoch 4/100
687/687 [==============================] - 3s 5ms/step - loss: 0.4394 - acc: 0.8285 - val_loss: 0.4116 - val_acc: 0.8388 - lr: 0.0100
Epoch 5/100
687/687 [==============================] - 4s 6ms/step - loss: 0.4310 - acc: 0.8291 - val_loss: 0.4033 - val_acc: 0.8373 - lr: 0.0100
Epoch 6/100
687/687 [==============================] - 3s 4ms/step - loss: 0.4258 - acc: 0.8300 - val_loss: 0.4181 - val_acc: 0.8372 - lr: 0.0100
Epoch 7/100
687/687 [==============================] - 3s 5ms/step - loss: 0.4275 - acc: 0.8313 - val_loss: 0.4034 - val_ac

In [17]:
model.save("2layerDNN")

In [18]:
from tensorflow.keras.models import load_model
loaded_model = load_model('2layerDNN')

In [19]:
loaded_model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 128)               11776     
                                                                 
 batch_normalization_3 (Bat  (None, 128)               512       
 chNormalization)                                                
                                                                 
 re_lu_3 (ReLU)              (None, 128)               0         
                                                                 
 dropout_3 (Dropout)         (None, 128)               0         
                                                                 
 dense_7 (Dense)             (None, 1)                 129       
                                                                 
Total params: 12417 (48.50 KB)
Trainable params: 12161 (47.50 KB)
Non-trainable params: 256 (1.00 KB)
__________________